[workspace]
members = [
    "crates/core",
    "crates/backend",
    "crates/server",
    "apps/server-cli",
    "apps/client-cli",
]
resolver = "3"

[workspace.dependencies]
# Error handling.
anyhow = { version = "1.0.97", features = ["backtrace"] }
thiserror = "2.0.12"

# Code generator.
derive_more = { version = "2.0.1", features = ["full"] }
typed-builder = "0.21.0"

# Async.
tokio = { version = "1", features = ["full"] }

# Random ID.
svix-ksuid = "0.8.0"

# Time.
time = { version = "0.3.41", features = ["parsing", "formatting", "serde"] }

# Logging.
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# File system.
dirs = "6.0.0"

# JSON serializer.
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"

# Parser combinator.
nom = "8.0.0"

# CLI.
clap = { version = "4.5.35", features = ["derive"] }

# SQL.
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "time", "migrate"] }

# HTTP server.
axum = { version = "0.8.4", features = ["macros"]}