[workspace]
members = [
    "crates/core",
    "crates/backend",
    "crates/http-server",
    "apps/server-cli",
    "apps/client-cli",
]
resolver = "3"

[workspace.dependencies]
# Utility.
anyhow = "1.0.97"
nom = "8.0.0"
svix-ksuid = "0.8.0"
thiserror = "2.0.12"
time = "0.3.41"
tokio = "1"
typed-builder = "0.21.0"

# CLI.
clap = "4.5.35"

# SQL.
sqlx = "0.8"
