* Silver-Brain

A concept map based personal knowledge system.

Key features:
- Backend implemented in Rust. Fast, reliable and easy to deploy.
- C/S architecture makes it easy to implement any front-end UI.
- SQLite based storage makes it convenient to backup and/or sync among multiple machines.
- Emacs UI with hydra based interaction system and corresponding hotkeys.
- Supports Org, Markdown and any formats that your Emacs supports.

** Overview

*** Prologue

Back to the time when I was a student, when final examination came, I would write down all the concepts on an A4 paper and draw lines among them. I used this method for years to help myself organize what I have learned during a term and get prepared for the exams. After becoming a professional engineer, I also often feel the need to note about "how to hack this" or "how to configure that". I need a place to record all these knowledge, for myself.

I recall I started to use it since 2014 (and started to upload my Emacs configuration to [[https://github.com/sheepduke/emacs-config][emacs-config]] repo since 2017). Org Mode was a natural choice for me. Having been using it for quite some years, I found with pity that the underlying storage of Org Mode, i.e. unstructured data on hard disks, has many limitations when:

1. Creating cross links or references among multiple entries.

   Well, technically you could, but:
   - When using human readable names as file names, it is not easy to rename a file without breaking all the references.
   - When using UUID names as file names, it is not easy to tell the content from the file name and/or reference it from elsewhere.
     
2. Searching for an entry.

   You may use agenda, but then you have to put multiple files into the agenda list. Alternatively, you can just grep everything but that is too bare-bone. Either way, it is not easy to search complex scenarios.

3. Analyzing the entries with a program.

   A Org Mode file is simply a plain text file with its own format, which is not programming friendly. You can, for sure, write Emacs Lisp code to achieve this but IMHO using Emacs Lisp does not make much sense unless hacking Emacs itself.

I also investigated other Org based solutions including org-brain and more, but did not yet find one that checks all the boxes.

Please do not get me wrong. I still use Emacs (and the Org Mode) every day, but using plain files to manage a personal knowledge base does not really scale well.

Being inspired by [[https://www.thebrain.com/][TheBrain]], I developed this software.

*** Getting Started

1. Install =Cargo= and build the project by running =cargo build --release= in the root directory. The output executable file will be put under =target/release/server-cli=.
2. Install the =emacs/= directory to your Emacs load path.
3. Run =server-cli= to start the server. Pass =--help= argument to see more information.
4. Run =silver-brain-list-items= to search and list items.

*** Change Log

Please refer to [[./CHANGELOG.org][CHANGELOG.org]].

** Basic Concepts

** User Manual
