CREATE TABLE IF NOT EXISTS concept(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid VARCHAR(64) NOT NULL,
  name VARCHAR(1024) NOT NULL,
  content VARCHAR(1024) NOT NULL,
  content_format VARCHAR(16) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS concept_relation (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source VARCHAR(64) NOT NULL,
  target VARCHAR(64) NOT NULL,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);
