name:                silver-brain
version:             0.1.0.0
github:              "githubuser/silver-brain"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/silver-brain#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- directory
- filepath
- http-types
- scotty
- sqlite-simple
- string-conversions
- text
- time
- uuid

library:
  source-dirs: src
  default-extensions:
    - DuplicateRecordFields
    - ImportQualifiedPost
    - NamedFieldPuns
    - OverloadedStrings
    - OverloadedRecordDot

executables:
  silver-brain-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - silver-brain

tests:
  silver-brain-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - silver-brain
