//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::attachment::Entity as Attachment;
pub use super::entry::Entity as Entry;
pub use super::entry_tag::Entity as EntryTag;
pub use super::link::Entity as Link;
