//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::attachment::Entity as Attachment;
pub use super::entry::Entity as Entry;
pub use super::friend_link::Entity as FriendLink;
pub use super::parent_link::Entity as ParentLink;
