[package]
name = "silver-brain-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
sqlx.workspace = true
svix-ksuid.workspace = true
time.workspace = true
tokio.workspace = true

silver-brain-core = { path = "../core" }

[dev-dependencies]
typed-builder.workspace = true