[package]
name = "silver-brain-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
nom.workspace = true
svix-ksuid.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
time.workspace = true
typed-builder.workspace = true