[package]
name = "silver-brain-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true, features = [ "backtrace" ]}
nom = { workspace = true }
svix-ksuid = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = ["parsing", "formatting"] }
